# Generated by Django 4.0.3 on 2022-03-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
